//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_FileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public L_FileUpload()
        {
            this.M_Product_Image = new HashSet<M_Product_Image>();
            this.T_PaymentNotification = new HashSet<T_PaymentNotification>();
        }
    
        public long id { get; set; }
        public string fileName { get; set; }
        public string ipAddress { get; set; }
        public string macAddress { get; set; }
        public string type { get; set; }
        public System.DateTime uploadDate { get; set; }
        public Nullable<int> userId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Product_Image> M_Product_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PaymentNotification> T_PaymentNotification { get; set; }
    }
}
