//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Product()
        {
            this.M_Product_Image = new HashSet<M_Product_Image>();
            this.T_Order = new HashSet<T_Order>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string detail { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> isPreOrder { get; set; }
        public bool isUseStock { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> preEnd { get; set; }
        public Nullable<System.DateTime> preStart { get; set; }
        public Nullable<decimal> price { get; set; }
        public bool isShipping { get; set; }
        public int qtyShippingPriceCeiling { get; set; }
        public decimal shippintPriceRate { get; set; }
        public string unitName { get; set; }
        public Nullable<int> updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<decimal> weight { get; set; }
        public bool isDelete { get; set; }
        public bool isManualPickup { get; set; }
        public string pickupAt { get; set; }
        public Nullable<int> stockQrty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Product_Image> M_Product_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Order> T_Order { get; set; }
    }
}
