//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Product_Image
    {
        public int id { get; set; }
        public long fileId { get; set; }
        public int productId { get; set; }
    
        public virtual L_FileUpload L_FileUpload { get; set; }
        public virtual M_Product M_Product { get; set; }
    }
}
