//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_RoleMapping
    {
        public long id { get; set; }
        public string role { get; set; }
        public int userId { get; set; }
    
        public virtual S_Role S_Role { get; set; }
        public virtual S_User S_User { get; set; }
    }
}
