//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_User()
        {
            this.S_RoleMapping = new HashSet<S_RoleMapping>();
        }
    
        public int userId { get; set; }
        public int createBy { get; set; }
        public System.DateTime createDate { get; set; }
        public string displayName { get; set; }
        public string email { get; set; }
        public bool isActive { get; set; }
        public string password { get; set; }
        public int updateBy { get; set; }
        public System.DateTime updateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_RoleMapping> S_RoleMapping { get; set; }
    }
}
