//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaymentNotification
    {
        public int id { get; set; }
        public long fileId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string orderCode { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string paymentType { get; set; }
        public bool isActive { get; set; }
        public bool isMapping { get; set; }
        public decimal money { get; set; }
    
        public virtual L_FileUpload L_FileUpload { get; set; }
    }
}
