//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salmorn_admin.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductStocks
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int productId { get; set; }
        public int qty { get; set; }
    }
}
