//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWarNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order
    {
        public int id { get; set; }
        public string orderNo { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public int numTicket { get; set; }
        public string identNo { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<bool> isSendPaySlip { get; set; }
        public Nullable<System.DateTime> sendPaySlipDate { get; set; }
        public Nullable<bool> isApprovePayment { get; set; }
        public Nullable<System.DateTime> approvePaymentDate { get; set; }
        public string approvePaymentBy { get; set; }
        public string slipPath { get; set; }
    }
}
