//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWarNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Slip
    {
        public string orderNo { get; set; }
        public int seq { get; set; }
        public string slipPath { get; set; }
        public bool isApprove { get; set; }
        public System.DateTime uploadDate { get; set; }
    }
}
